export const permissions = [
  "VIEW_DASHBOARD",
  "MANAGE_USERS",
  "MANAGE_COMPANIES",
  "MANAGE_COURSES",
  "MANAGE_LIVE_CLASSES",
  "MANAGE_CERTIFICATES",
  "MANAGE_PAYMENTS",
  "MANAGE_REPORTS",
  "MANAGE_SETTINGS"
];
