export const streamingFeatures = [
  "HD_VIDEO",
  "4K_VIDEO",
  "SCREEN_SHARING",
  "SLIDE_PRESENTATION",
  "WHITEBOARD",
  "LIVE_CHAT",
  "QUESTIONS_AND_ANSWERS",
  "HAND_RAISE",
  "BREAKOUT_ROOMS",
  "ATTENDANCE_TRACKING",
  "AUTO_RECORDING",
  "NOISE_CANCELLATION",
  "MICROPHONE_CONTROL",
  "CAMERA_CONTROL"
];
