export const trainingTypes = [
  "WORKPLACE_SAFETY",
  "TECHNICAL_TRAINING",
  "LEADERSHIP",
  "COMPLIANCE",
  "HEALTH_AND_SAFETY",
  "ENVIRONMENTAL",
  "FIRST_AID",
  "FIRE_SAFETY",
  "CUSTOM_TRAINING"
];
